stages:
  - test
  - build

test-lint:
  stage: test
  script:
    - bun i
    - bun test:lint

test-unit:
  stage: test
  script:
    - bun i
    - bun test:unit

build:
  stage: build
  script:
    - bun i
    - bun build