stages:
  - install_dependencies
  - test
  - build

install_dependencies:
  stage: install_dependencies
  script:
    - bun i

test-lint:
  stage: test
  script:
    - bun test:lint

test-unit:
  stage: test
  script:
    - bun test:unit

build:
  stage: build
  script:
    - bun build