version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres #update this
      POSTGRES_PASSWORD: password #update this
      POSTGRES_DB: mydb #update this

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8181:80"
    volumes:
      - /home/pgadmin:/var/lib/pgadmin #update this

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025" # Web port pour MailHog interface
      - "1025:1025" # SMTP port fort MailHog

  redis: # for the Worker (Bullmq)
    image: redis:latest
    ports:
      - "6379:6379"
